### ISSUE TITLE
Integration needs custom field

### ISSUE THREAD

**Issue by LauraStatik** [digitalpulsebe/craft-formie-flexmail#1]
When trying to submit a form with a Flexmail intergration, we got the following error:
![Screenshot 2023-12-04 at 15 20 03](https://github.com/digitalpulsebe/craft-formie-flexmail/assets/98809662/3278ff12-0814-4c9d-9a90-68d834ae69a8)

Turns out that the Flexmail did not contain custom fields. After adding a random custom field in Flexmail, the form worked as expected.

Craft CMS version: 4.5.11.1
Formie version: 2.0.43
Flexmail for Formie version: 1.0.1

**Comment by jodeba** [comment]
Hi, thank you for pointing out! I will try to alter the submission request in case no custom fields are present in the Flexmail account.

**Comment by jodeba** [comment]
Hi, this is fixed in [1.0.2](https://github.com/digitalpulsebe/craft-formie-flexmail/releases/tag/1.0.2)
