### ISSUE TITLE
Opt in from form field

### ISSUE THREAD

**Issue by WHITE-developer** [digitalpulsebe/craft-formie-flexmail#2]
Is there a way to do an opt in based on a form field, like in the Mailchimp integration?

![image](https://github.com/digitalpulsebe/craft-formie-flexmail/assets/22771556/e9489f73-555d-4aca-a7ba-5e7daf79c210)

**Comment by bartdigitalpulse** [comment]
Hi @WHITE-developer,
The developer is on holiday until next week. He'll get back to you on monday.

**Comment by jodeba** [comment]
Hi @WHITE-developer, 
it is not available at the moment, but it sounds like a good idea. I'll try to add it soon!

**Comment by jodeba** [comment]
Please update the package to 1.0.3 to use this feature.
